{
 "title": "ACH Demo",
 "time": { "from": "2020-03-10T21:32:29.441Z", "to": "2020-03-10T21:34:01.198Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "ach" }
  ]
 },
 "panels": [
  { "title": "Pipeline realtime view", "type": "larona-epict-panel", "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Transactions value",
   "type": "graph",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Total amount" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  balance\nFROM bank_balance\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployments and Jobs",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    },
    {
     "expr": "kube_job_status_active{namespace=~\"$namespace\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  }
 ]
}