{
 "title": "ACH Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "ach" }
  ]
 },
 "panels": [
  {
   "title": "Pipeline progress",
   "type": "larona-epict-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  sum(entry) AS \"transactions\"\nFROM merchant_upload"
    },
    {
     "rawSql": "SELECT\n  time,\n  sum(entry) AS \"odfi_split\"\nFROM odfi_split"
    },
    {
     "rawSql": "SELECT\n  time,\n  sum(entry) AS \"rdfi_split\"\nFROM rdfi_split"
    },
    {
     "rawSql": "SELECT\n  time,\n  sum(entry) AS \"rdfi_process\"\nFROM rdfi_process"
    }
   ]
  },
  {
   "title": "Transactions combined amount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD", "label": "Total amount" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  balance\nFROM bank_balance\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Deployments and Jobs",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\",deployment!~\"grafana.*|my-cluster.*\"}",
     "legendFormat": "{{ deployment }}"
    },
    {
     "expr": "kube_job_status_active{namespace=~\"$namespace\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(pod:container_cpu_usage:sum{pod=~'kafkasource-odfi-split.*',namespace=\"$namespace\"})",
     "legendFormat": "kafkasource-odfi-split"
    },
    {
     "expr": "sum(pod:container_cpu_usage:sum{pod=~'kafkasource-rdfi-split.*',namespace=\"$namespace\"})",
     "legendFormat": "kafkasource-rdfi-split"
    },
    {
     "expr": "sum(pod:container_cpu_usage:sum{pod=~'kafkasource-rdfi-process.*',namespace=\"$namespace\"})",
     "legendFormat": "kafkasource-rdfi-process"
    },
    {
     "expr": "sum(pod:container_cpu_usage:sum{pod=~'create-.*',namespace=\"$namespace\"})",
     "legendFormat": "create-transaction"
    },
    {
     "expr": "sum(pod:container_cpu_usage:sum{pod=~'odfi-split.*',namespace=\"$namespace\"})",
     "legendFormat": "odfi-split"
    },
    {
     "expr": "sum(pod:container_cpu_usage:sum{pod=~'rdfi-split.*',namespace=\"$namespace\"})",
     "legendFormat": "rdfi-split"
    },
    {
     "expr": "sum(pod:container_cpu_usage:sum{pod=~'rdfi-process.*',namespace=\"$namespace\"})",
     "legendFormat": "rdfi-process"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'kafkasource-odfi-split.*',namespace=\"$namespace\"})",
     "legendFormat": "kafkasource-odfi-split"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'kafkasource-rdfi-split.*',namespace=\"$namespace\"})",
     "legendFormat": "kafkasource-rdfi-split"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'kafkasource-rdfi-process.*',namespace=\"$namespace\"})",
     "legendFormat": "kafkasource-rdfi-process"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'create-transaction.*',namespace=\"$namespace\"})",
     "legendFormat": "create-transaction"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'odfi-split.*',namespace=\"$namespace\"})",
     "legendFormat": "odfi-split"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'rdfi-split.*',namespace=\"$namespace\"})",
     "legendFormat": "rdfi-split"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'rdfi-process.*',namespace=\"$namespace\"})",
     "legendFormat": "rdfi-process"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\",pod!~'my-cluster.*|maria.*|grafana.*|kafdrop.*'})",
     "legendFormat": "{{ deployment }}"
    }
   ]
  }
 ]
}