apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: risk-assessment-build
spec:
  resources:
  - name: git-repo
    type: git
  - name: push-image
    type: image
  tasks:
  - name: buildah
    taskRef:
      name: build-image
      kind: Task
    resources:
      inputs:
      - name: source
        resource: git-repo
      outputs:
      - name: image
        resource: push-image
    params:
    - name: DOCKERFILE
      value: './demos/xrayedge/containers/risk-assessment/Dockerfile'
    - name: CONTEXT
      value: './demos/xrayedge/containers/risk-assessment'
    - name: TLSVERIFY
      value: 'false'
