{
 "title": "XRay Lab",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "${namespace}" }
  ]
 },
 "panels": [
  {
   "title": "Pipeline progress",
   "type": "larona-epict-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time,count(name)-1 AS \"images_uploaded\"\nFROM images_uploaded"
    },
    {
     "rawSql": "SELECT time,count(name)-1 AS \"images_processed\"\nFROM images_processed"
    },
    {
     "rawSql": "SELECT time,count(name)-1 AS \"images_anonymized\"\nFROM images_anonymized"
    }
   ]
  },
  {
   "title": "Last 10 uploaded images",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM images_uploaded WHERE name != '' ORDER by time DESC LIMIT 10"
    }
   ]
  },
  { "title": "Last uploaded image", "type": "ryantxu-ajax-panel", "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "Last 10 processed images",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT time,name FROM images_processed WHERE name != '' ORDER by time DESC LIMIT 10"
    }
   ]
  },
  { "title": "Last processed image", "type": "ryantxu-ajax-panel", "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 } },
  {
   "title": "CPU  and RAM Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "CPU" }
   ],
   "targets": [
    {
     "expr": "sum(pod:container_cpu_usage:sum{namespace=\"$namespace\"})",
     "legendFormat": " CPU"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Risk assessment containers running",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\"risk-assessment.*\",namespace=~\"$namespace\"})",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Risk distribution",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  label AS metric,\n  count(label)\nFROM images_processed\nWHERE\n  $__timeFilter(time)\n  and\n  label != ''\nGROUP BY 1,2\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Last 10 anonymized images",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT * FROM images_anonymized WHERE name != '' ORDER by time DESC LIMIT 10"
    }
   ]
  },
  { "title": "Last anonymized image", "type": "ryantxu-ajax-panel", "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 } },
  {
   "title": "Deployments",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=~\"risk-assessment.*\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Images processed by model version",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  model AS metric,\n  count(model) AS \"model\"\nFROM images_processed\nWHERE\n  $__timeFilter(time)\n  and\n  model != ''\nGROUP BY 1,2\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  }
 ]
}