apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: rdfi-split
  namespace: ach
spec:
  bootstrapServers:
    - 'my-cluster-kafka-bootstrap.ach:9092'
  consumerGroup: rdfi-split
  sink:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: rdfi-split
  topics:
    - odfi
