apiVersion: serving.knative.dev/v1 
kind: Service
metadata:
  name: rdfi-split
  namespace: ach
spec:
  template:
    metadata:
        annotations:
          autoscaling.knative.dev/target: '2'
    spec:
      containers:
      - image: quay.io/guimou/ach-rdfi-split:latest
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: AWS_ACCESS_KEY_ID 
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: AWS_SECRET_ACCESS_KEY 
        - name: service_point
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: service_point 
        - name: database-user
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-user
        - name: database-password
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-password
        - name: database-host
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-host
        - name: database-db
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-db
        resources:
          limits:
            cpu: '2'
            memory: 1G
          requests:
            cpu: 400m
            memory: 100M

