apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: create-transaction
  name: create-transaction
  namespace: ach
spec:
  backoffLimit: 6
  completions: 60
  parallelism: 5
  successfulJobsHistoryLimit: 0
  template:
    metadata:
      labels:
        job-name: create-transaction
      name: create-transaction
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: AWS_ACCESS_KEY_ID 
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: AWS_SECRET_ACCESS_KEY 
        - name: service_point
          value: 'replace_me'
        image: quay.io/guimou/ach-transactions-generator:latest
        imagePullPolicy: Always
        name: gen
        resources: {}
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 15

